### ISSUE TITLE
Documentation is missing tslib requirement

### ISSUE THREAD

**Issue by Julien-Marcou** [remojansen/InversifyJS#1391]
I wanted to add dependency injections to a project that didn't need tslib, after adding inversify (and reflect-metadata), my dependency injection were working fine until I tried to build the project for a production release and run it :

```
Error: Cannot find module 'tslib'
Require stack:
- /var/www/nodejs/my-app/app.js
- /var/www/nodejs/my-app/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/www/nodejs/my-app/app.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
```

The generated code for `app.js` is:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.App = void 0;
const tslib_1 = require("tslib");
const inversify_1 = require("inversify");
const http_server_1 = require("./services/http-server");
let App = class App {
    httpServer;
    constructor(httpServer) {
        this.httpServer = httpServer;
    }
    start() {
        this.httpServer.start();
    }
    stop() {
        this.httpServer.stop();
    }
};
App = (0, tslib_1.__decorate)([
    (0, inversify_1.injectable)(),
    (0, tslib_1.__param)(0, (0, inversify_1.inject)(http_server_1.HttpServer)),
    (0, tslib_1.__metadata)("design:paramtypes", [http_server_1.HttpServer])
], App);
exports.App = App;
```

So, it looks like tslib is required to make inversify works on production environment, but the documentation/readme of inversify does not mention anything about it.

**Comment by notaphplover** [comment]
This is not related to inversify. Inversify does not rely on `tslib`. You probably have [importHelpers](https://www.typescriptlang.org/tsconfig/#importHelpers) option enabled in your typescript config.

Closing the issue as not related to inversify.
