### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Bortnyak** [remojansen/InversifyJS#1475]
Sometimes I face this issue in different environments (ubuntu 20.04 and macOS Monterey):
'TypeError: Cannot read properties of undefined (reading 'length')'

 Did anybody face the same issue?

## Environment
* Node v16.16.0 (tried 14/18 and got the same)
* yarn v1.22.19
* macOS Monterey
* "inversify": "^5.0.1",
* "inversify-express-utils": "6.3.2",

# Stack trace
```
TypeError: Cannot read properties of undefined (reading 'length')
    at pathtoRegexp (/Users/volodymyr/Documents/repos/observe-api/node_modules/path-to-regexp/index.js:63:49)
    at new Layer (/Users/volodymyr/Documents/repos/observe-api/node_modules/inversify-express-utils/node_modules/express/lib/router/layer.js:45:17)
    at Function.use (/Users/volodymyr/Documents/repos/observe-api/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:464:17)
    at Function.<anonymous> (/Users/volodymyr/Documents/repos/observe-api/node_modules/inversify-express-utils/node_modules/express/lib/application.js:220:21)
    at Array.forEach (<anonymous>)
    at Function.use (/Users/volodymyr/Documents/repos/observe-api/node_modules/inversify-express-utils/node_modules/express/lib/application.js:217:7)
    at InversifyExpressServer.registerControllers (/Users/volodymyr/Documents/repos/observe-api/node_modules/inversify-express-utils/lib/server.js:161:19)
    at InversifyExpressServer.build (/Users/volodymyr/Documents/repos/observe-api/node_modules/inversify-express-utils/lib/server.js:121:14)
    at Object.<anonymous> (/Users/volodymyr/Documents/repos/observe-api/dist/App.js:68:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
error Command failed with exit code 1.
```

**Comment by Bortnyak** [comment]
Figured out that this issue happens when do not specify the `rootPath` param. Here is my inversify server config
```
let server = new InversifyExpressServer(
  container,
  null,
  { rootPath: config.apiRootPath },
  null,
  null
);
```
Here I specified the `rootPath` param but forgot to set it in my config.

**Comment by notaphplover** [comment]
Hey @Bortnyak, could provide a minimum reproduction code? Consider sharing a [code sandbox](https://codesandbox.io) or a repreoduction repo.

**Comment by Bortnyak** [comment]
@notaphplover Hey. It took me a while to remember what the issue was: 
the reason for that crash was that I didn't specify api root path parameter when creating a container like this:

```
import { InversifyExpressServer } from 'inversify-express-utils';
import { Container } from 'inversify';

const container = new Container();
// ... bindings

const server = new InversifyExpressServer(container, null, {
    rootPath: process.env.apiRootPath // while having it empty in the env
});

const app = server.build();
```
So, the issue is not in the Inversify.js itself. Anyway, thanks for getting back to this.
Is this project going to active development/maintenance mode again? 
If there are good-first-issues I would like to participate.

upd.:
Github acted weird, and only now have the previous comments appeared:
https://github.com/inversify/InversifyJS/issues/1475#issuecomment-1199999918

**Comment by notaphplover** [comment]
Hey @Bortnyak, thank you for your message.

> So, the issue is not in the Inversify.js itself

Then I'll proceed to close the issue :smiley:.

> Is this project going to active development/maintenance mode again?

Yeah, I'm working on solving technical debt in the core of the container while migrating it to the [monorepo](https://github.com/inversify/monorepo/) repository.

> If there are good-first-issues I would like to participate.

I think I already solve most of those issues. I'm more than happy to be assisted though. Setting up a docusaurus site as a monorepo package or setting the foundation of some e2e test on top of cucumberJS are some of the next tasks to be accomplished. I know they're not the most exciting tasks ever but if you feel like going for it I can do some analysis and prepare some tasks.

**Comment by Bortnyak** [comment]
@notaphplover Yup, just let me know where I can start from

**Comment by notaphplover** [comment]
Hey @Bortnyak, I just submitted https://github.com/inversify/monorepo/issues/156. We can start from there and build a nice documentation site :smiley:
