### ISSUE TITLE
[inversify-restify-utils] package does not work with node 18 because of outdated dependency

### ISSUE THREAD

**Issue by acommodari** [remojansen/InversifyJS#1489]
I would like for `inversify-restify-utils` to update its dependency on `restify` to allow for projects that use it to work in `node@18`

(I am willing to create a PR)

## Expected Behavior

Upgrade to `node@18` and `restify@10` and for my app to run correctly. 

## Current Behavior

My app does not run in `node@18` because of `inversify-restify-utils` since it depends on a version of `restify` that does not work with `node@18` (i.e. `restify` < v10)

## Possible Solution

1. update the `restify` dependency to version 10 with a major version update.
2. if this is gonna be a major version update anyway why not go the route of `restify-swagger-jsdoc` and set `restify` as a peerDependency `>= 10` to avoid similar issues in the future?

## Steps to Reproduce (for bugs)

1. create a node app using `node@18` and `restify@10`
2. install `inversify-restify-utils@latest` 
3. run the app

## Context

We want to use `node@18` in our app at work however this package is blocking us from doing so.

## Your Environment

* Version used: `inversify-restify-utils@3.5.0`
* Environment name and version (e.g. Chrome 39, node.js 5.4): `node@18` and Chrome 107
* Operating System and version (desktop or mobile): macOS 12.6
* Link to your project:

# Stack trace

(known issue with `restify` < v10)
```
TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/inversify-restify-utils/node_modules/restify/lib/request.js:848:30)
    at Object.<anonymous> (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/inversify-restify-utils/node_modules/restify/lib/server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/inversify-restify-utils/node_modules/restify/lib/index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/inversify-restify-utils/lib/server.js:22:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/inversify-restify-utils/lib/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/tests/unit/AppTest.ts:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.exports.requireOrImport (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/mocha/lib/nodejs/esm-utils.js:49:16)
    at async Object.exports.loadFilesAsync (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
    at async singleRun (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/alessandro.commodari/ssense/workspace/services/ag-shipping/node_modules/mocha/lib/cli/run.js:370:5)
```

**Comment by PodaruDragos** [comment]
Hello, 
This package is really outdated, in order to update that we first need to remove gulp, and built it through tsc or similar.
If anyone is up to that task feel free to send a PR, following the code in `inversify-express-utils`

**Comment by acommodari** [comment]
> Hello, This package is really outdated, in order to update that we first need to remove gulp, and built it through tsc or similar. If anyone is up to that task feel free to send a PR, following the code in `inversify-express-utils`

@PodaruDragos cool good to know I'll try and find some free time to do this revamp hopefully i can get to it soon 🙏 I think its definitely needed
Curious if in the meantime it would be okay to publish a version with just the updated `restify` dependency so that it unblocks people moving to node 18? 🤔 I can take another look since even though this change would bump `restify` by 2 major versions I don't think it breaks anything in the decorator lib so this might not even need a major version bump only maybe a minor 
but we can still make it major just to be safe

**Comment by PodaruDragos** [comment]
we can definitely check that. I can merge PR's and what not, but I don't have the rights to publish a new release.

**Comment by acommodari** [comment]
@PodaruDragos I have created a PR please have a look. 😁
