### ISSUE TITLE
Attempting to construct 'Symbol(BaseHttpServer)' in a synchronous way, but it has asynchronous dependencies

### ISSUE THREAD

**Issue by SirMishaa** [remojansen/InversifyJS#1494]
Hello, I've started a project and I'm using Inversify, it's working good but when I try to bind / retrice my http server instance, I have errors : 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/42717232/210030114-922d3265-1a01-4822-9552-7def867b3068.png">

Code is available here (there are just 3 files) : 
==> https://gist.github.com/SirMishaa/c0da04d5c93b6c5cfd84836d39879ec1 <==

I'm a beginner with Fastify, so I may doing something wrong 
If it's really hard to debug, I can commit, push and send you I link to the repository (if it's really needed)

Thank you <3

## Current Behavior
I got an error If I don't use .toString for Symbol (other usage of `container.get` works without it) : 
```ts
const httpServer = container.get<FastifyInstance>(TYPES.BaseHttpServer)
```
Error: 
```
[03:57:02.542] FATAL (64088): Cannot convert a Symbol value to a string
    err: {
      "type": "TypeError",
      "message": "Cannot convert a Symbol value to a string",
      "stack":
          TypeError: Cannot convert a Symbol value to a string
              at Object.LAZY_IN_SYNC (/Users/mishaa/dev/hexa-node/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/lib/constants/error_msgs.js:25:80)
              at Container._getButThrowIfAsync (/Users/mishaa/dev/hexa-node/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/lib/container/container.js:595:40)
              at Container.get (/Users/mishaa/dev/hexa-node/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/lib/container/container.js:374:21)
              at file:///Users/mishaa/dev/hexa-node/dist/index.js:95:32
              at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
    }
```
Fixed by using `TYPES.x.toString()` but why ? I don't have to do that for other usage of container

And the most important one, I got the following error :
```ts
[03:57:21.954] FATAL (64157): You are attempting to construct 'Symbol(BaseHttpServer)' in a synchronous way
 but it has asynchronous dependencies.
    err: {
      "type": "Error",
      "message": "You are attempting to construct 'Symbol(BaseHttpServer)' in a synchronous way\n but it has asynchronous dependencies.",
      "stack":
          Error: You are attempting to construct 'Symbol(BaseHttpServer)' in a synchronous way
           but it has asynchronous dependencies.
              at Container._getButThrowIfAsync (/Users/mishaa/dev/hexa-node/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/lib/container/container.js:595:19)
              at Container.get (/Users/mishaa/dev/hexa-node/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/lib/container/container.js:374:21)
              at file:///Users/mishaa/dev/hexa-node/dist/index.js:95:32
              at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
    }

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 6.0.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 19, PNPM, TS 4.9, TSUP 6.4
* Operating System and version (desktop or mobile): MacOS Ventura 13.1
* Link to your project: https://github.com/SirMishaa/hexa-node **(Change for implementation of IoC have not been pushed yet)**

# Stack trace

**Comment by SirMishaa** [comment]
It looks like it's working when I wrap the result of the function into an object 
```ts
container.bind<{ instance: FastifyInstance }>(TYPES.BaseHttpServer).toConstantValue(
	{
		instance: createHttpServer({
			httpServerConfiguration: {
				logger,
			},
			routes: routes(),
			logger,
		}),
	},
)

// Usage
const httpServer = container.get<{ instance: FastifyInstance }>(TYPES.BaseHttpServer).instance
```

Someone can explain why? I'd like to understand

**Comment by SirMishaa** [comment]
Oh, it looks like it's working also If I use ``await container.getAsync<FastifyInstance>(TYPES.BaseHttpServer)``, with this approach, I don't have to wrap to an object when binding. 

I'm not sure to understand why because the function is not `async` and do not return a `Promise`.

**Comment by SirMishaa** [comment]
Ok, that my bad, it looks like I have this error because the creation of an instance of Fastify returns a `PromiseLike<T>`, I assume that Fastify is using duck typing and throw an exception if the value is Async / Promise.
