### ISSUE TITLE
regression: inversify 6 no longer allows binding null values

### ISSUE THREAD

**Issue by simhnna** [remojansen/InversifyJS#1519]
Used to work in inversify 5

```
import { Container } from "inversify";

const container = new Container();
const s = Symbol('foo');
container.bind(s).toConstantValue(null);


console.log(container.get(s));
```

Produces:

```
/project/node_modules/inversify/lib/utils/binding_utils.js:62
        throw new Error(ERROR_MSGS.INVALID_BINDING_TYPE + " " + serviceIdentifierAsString);
              ^

Error: Invalid binding type: Symbol(foo)
    at ensureFullyBound (/project/node_modules/inversify/lib/utils/binding_utils.js:62:15)
    at _getResolvedFromBinding (/project/node_modules/inversify/lib/resolution/resolver.js:99:42)
    at /project/node_modules/inversify/lib/resolution/resolver.js:127:22
    at _resolveInScope (/project/node_modules/inversify/lib/resolution/resolver.js:121:14)
    at _resolveBinding (/project/node_modules/inversify/lib/resolution/resolver.js:126:12)
    at /project/node_modules/inversify/lib/resolution/resolver.js:88:20
    at resolve (/project/node_modules/inversify/lib/resolution/resolver.js:225:12)
    at /project/node_modules/inversify/lib/container/container.js:622:49
    at Container._get (/project/node_modules/inversify/lib/container/container.js:590:38)
    at Container._getButThrowIfAsync (/project/node_modules/inversify/lib/container/container.js:593:27)
```

**Comment by weyert** [comment]
Have you found a solution for this?

**Comment by simhnna** [comment]
You can wrap primitives `{ value: null }`

It's currently no longer a high priority for my projects. If I have time I might try creating a merge request that allows binding null values but understanding the code of inversofy isn't very easy...

**Comment by Jameskmonger** [comment]
Added to [milestone `6.0.3`](https://github.com/inversify/InversifyJS/milestone/18), we will aim to resolve this regression as a priority. cc @PodaruDragos

**Comment by notaphplover** [comment]
#1628 should fix this issue. The next release will have the patch :smiley:

**Comment by notaphplover** [comment]
Closing as fixed in `inversify@7`.
