### ISSUE TITLE
Tests for #549 are flaky (node 10 / es6)

### ISSUE THREAD

**Issue by Jameskmonger** [remojansen/InversifyJS#1526]
The tests for #549 are flaky on CI when running against `10.x` and `src/tsconfig-es6.json`

- https://github.com/inversify/InversifyJS/actions/runs/6163690582/job/16727801192
- https://github.com/inversify/InversifyJS/actions/runs/6163820009/job/16728207564

```
  1 failing

  1) Issue 549
       Should throw if circular dependencies found with dynamics:
     Error: Expected `willThrow` to throw:
- It looks like there is a circular dependency in one of the 'toDynamicValue' bindings. Please investigate bindings with service identifier 'Symbol(ADynamicValue)'.
or
- It looks like there is a circular dependency in one of the 'toDynamicValue' bindings. Please investigate bindings with service identifier 'Symbol(BDynamicValue)'.
but got
- Cannot read property 'rootRequest' of undefined
      at Context.it (test/bugs/issue_549.test.ts:65:15)
      at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by PodaruDragos** [comment]
honestly we should only test on 16+, since 16 is EOL.

**Comment by gustavohenke** [comment]
Weird, it's still broken locally for me on Node 20.x, but Node 18.x is fine.
