### ISSUE TITLE
postConstruct inconsistency for sync and async

### ISSUE THREAD

**Issue by dev-a-loper** [remojansen/InversifyJS#1545]
## Expected Behavior

post construct should act consistently for both async and sync post constructor functions

## Current Behavior

it reshapes the errors of the synchronous post constructor while leaving the errors of async ones as is

## Possible Solution

change the code that runs the post constructor and add an await like 
## Steps to Reproduce (for bugs)

1. create two separated classes one with synchronous and one with asynchronous postConstructor
2. throw error from both of them
3. see how they are different 

## Context

Well to be honest my problem is way worth 
I have a very very strange usecase and in my specific situation there are unhandled rejections after an error comes out of the method with postConstruct decorator
but I can't really reproduce it to show how it is  and I think fixing this issue will fix that too

## Your Environment

* Version used:6.0.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 18.17.1
* Operating System and version (desktop or mobile): linux ( nixos

# Stack trace

**Comment by notaphplover** [comment]
The errors are pretty much the same:

```ts
import 'reflect-metadata';
import { Container, preDestroy } from 'inversify';

class Foo {
  @preDestroy()
  public async preDestroy(): Promise<void> {
    throw new Error('Pre destroy error');
  }
}

const container: Container = new Container();

container.bind(Foo).toSelf().inSingletonScope();
container.get(Foo);

void (async () => {
  await container.unbindAsync(Foo);
})();
```
throws:

```
/project/workspace/node_modules/inversify/lib/container/container.js:524
                            throw new Error(ERROR_MSGS.ON_DEACTIVATION_ERROR((0, serialization_1.getServiceIdentifierAsString)(serviceIdentifier), ex_1.message));
                                  ^

Error: onDeactivation() error in class Foo: Pre destroy error
    at Container.<anonymous> (/project/workspace/node_modules/inversify/lib/container/container.js:524:35)
    at step (/project/workspace/node_modules/inversify/lib/container/container.js:67:23)
    at Object.throw (/project/workspace/node_modules/inversify/lib/container/container.js:48:53)
    at rejected (/project/workspace/node_modules/inversify/lib/container/container.js:40:65)
```

When the binding is syncronous:

```
/project/workspace/node_modules/inversify/lib/container/container.js:506
                throw new Error(ERROR_MSGS.ON_DEACTIVATION_ERROR((0, serialization_1.getServiceIdentifierAsString)(binding.serviceIdentifier), ex.message));
                ^

Error: onDeactivation() error in class Foo: Pre destroy error
    at Container._deactivate (/project/workspace/node_modules/inversify/lib/container/container.js:506:23)
    at Container._deactivateIfSingleton (/project/workspace/node_modules/inversify/lib/container/container.js:683:21)
    at Container._deactivateSingletons (/project/workspace/node_modules/inversify/lib/container/container.js:688:31)
    at Container.unbind (/project/workspace/node_modules/inversify/lib/container/container.js:270:18)
    at Object.<anonymous> (/project/workspace/lib/cjs/index.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
```

I'm closing the issue until we know more about the concrete use case and concrete examples.
